apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: virtual01
  namespace: ttcp
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "192.168.200.22"
  virtualServerPort: 5001
  mode: "performance"
  pool:
    service: ttcp-svc
    servicePort: 5001
    monitor:
      type: tcp
      interval: 5
      timeout: 16
