apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: virtual01
  namespace: test100
  labels:
    f5cr: "true"
spec:
  host: test01.example.com
  virtualServerAddress: "192.168.200.20"
  pools:
  - path: /coffee
    service: app-svc
    servicePort: 8080
    monitor:
      type: http
      send: "HTTP /rn"
      recv: ""
      interval: 20
      timeout: 10
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: virtual02
  namespace: test100
  labels:
    f5cr: "true"
spec:
  host: test01.example.com
  virtualServerAddress: "192.168.200.20"
  pools:
  - path: /tea
    service: app-svc
    servicePort: 8080
    monitor:
      type: http
      send: "HTTP /rn"
      recv: ""
      interval: 20
      timeout: 10
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: virtual01
  namespace: test101
  labels:
    f5cr: "true"
spec:
  host: test02.example.com
  virtualServerAddress: "192.168.200.21"
  pools:
  - path: /
    service: app-svc
    servicePort: 8080
    monitor:
      type: http
      send: "HTTP /rn"
      recv: ""
      interval: 20
      timeout: 10
