apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-5
  name: app-5
  namespace: cistest002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-5
  template:
    metadata:
      labels:
        app: app-5
    spec:
      containers:
      - image: cloudadc/cafe:2.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: cistest002
    cis.f5.com/as3-app: app-5
    cis.f5.com/as3-pool: app-5_svc_pool
  name: app-svc-5
  namespace: cistest002
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-5
  sessionAffinity: None
  type: ClusterIP

