apiVersion: v1
kind: Namespace
metadata:
  name: cistest004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-1
  name: app-1
  namespace: cistest004
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: cistest004
    cis.f5.com/as3-app: app-1
    cis.f5.com/as3-pool: app_1_svc_pool
  name: app-svc-1
  namespace: cistest004
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-1
  sessionAffinity: None
  type: ClusterIP

