apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: exdns
  labels:
    f5cr: "true"
spec:
  domainName: arcadia-finance.io
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - name: arcadia-finance.io

