apiVersion: v1
kind: Namespace
metadata:
  labels:
    cis_scanner_zone: zone_1
  name: arcadia-main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  namespace: arcadia-main
  labels:
    app: main
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
      version: v1
  template:
    metadata:
      labels:
        app: main
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: main-svc
        image: cloudadc/arcadia-main:1.1
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: main-svc
  namespace: arcadia-main
  labels:
    app: main
    cis.f5.com/as3-tenant: "arcadia-main"
    cis.f5.com/as3-app: "main"
    cis.f5.com/as3-pool: "main-svc-pool"
spec:
  type: ClusterIP
  ports:
  - name: main-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: main
