apiVersion: v1
kind: Namespace
metadata:
  labels:
    cis_scanner_zone: zone_1
  name: arcadia-refer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: refer
  namespace: arcadia-refer
  labels:
    app: refer
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: refer
      version: v1
  template:
    metadata:
      labels:
        app: refer
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: refer-svc
        image: cloudadc/arcadia-refer:1.0
        imagePullPolicy: IfNotPresent
        name: refer
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: refer-svc
  namespace: arcadia-refer
  labels:
    app: refer
    cis.f5.com/as3-tenant: "arcadia-refer"
    cis.f5.com/as3-app: "refer"
    cis.f5.com/as3-pool: "refer-svc-pool"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: refer-80
  selector:
    app: refer
