apiVersion: v1
kind: Namespace
metadata:
  labels:
    cis_scanner_zone: zone_1
  name: arcadia-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: arcadia-backend
  labels:
    app: backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: backend-svc
        image: cloudadc/arcadia-backend:1.0
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: arcadia-backend
  labels:
    app: backend
    cis.f5.com/as3-tenant: "arcadia-backend"
    cis.f5.com/as3-app: "backend"
    cis.f5.com/as3-pool: "backend-svc-pool"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: backend-80
  selector:
    app: backend
