apiVersion: v1
kind: Namespace
metadata:
  labels:
    cis_scanner_zone: zone_1
  name: arcadia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: arcadia
  labels:
    app: backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: backend-svc
        image: cloudadc/arcadia-backend:1.0
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: arcadia
  labels:
    app: backend
    cis.f5.com/as3-tenant: "arcadia"
    cis.f5.com/as3-app: "backend"
    cis.f5.com/as3-pool: "backend-svc-pool"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: backend-80
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  namespace: arcadia
  labels:
    app: main
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
      version: v1
  template:
    metadata:
      labels:
        app: main
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: main-svc
        image: cloudadc/arcadia-main:1.1
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: main-svc
  namespace: arcadia
  labels:
    app: main
    cis.f5.com/as3-tenant: "arcadia"
    cis.f5.com/as3-app: "main"
    cis.f5.com/as3-pool: "main-svc-pool"
spec:
  type: ClusterIP
  ports:
  - name: main-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: arcadia
  labels:
    app: api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      version: v1
  template:
    metadata:
      labels:
        app: api
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: api-svc
        image: cloudadc/arcadia-api:1.0
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: arcadia
  labels:
    app: api
    cis.f5.com/as3-tenant: "arcadia"
    cis.f5.com/as3-app: "api"
    cis.f5.com/as3-pool: "api-svc-pool"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: api-80
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: refer
  namespace: arcadia
  labels:
    app: refer
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: refer
      version: v1
  template:
    metadata:
      labels:
        app: refer
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: refer-svc
        image: cloudadc/arcadia-refer:1.0
        imagePullPolicy: IfNotPresent
        name: refer
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: refer-svc
  namespace: arcadia
  labels:
    app: refer
    cis.f5.com/as3-tenant: "arcadia"
    cis.f5.com/as3-app: "refer"
    cis.f5.com/as3-pool: "refer-svc-pool"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: refer-80
  selector:
    app: refer
