apiVersion: v1
kind: Namespace
metadata:
  labels:
    cis_scanner_zone: zone_1
  name: arcadia-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: arcadia-api
  labels:
    app: api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      version: v1
  template:
    metadata:
      labels:
        app: api
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: api-svc
        image: cloudadc/arcadia-api:1.0
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: arcadia-api
  labels:
    app: api
    cis.f5.com/as3-tenant: "arcadia-api"
    cis.f5.com/as3-app: "api"
    cis.f5.com/as3-pool: "api-svc-pool"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: api-80
  selector:
    app: api
