kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-arcadia-backend
  namespace: arcadia-backend
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.30.0",
        "id": "arcadia-backend",
        "arcadia-backend": {
          "class": "Tenant",
          "backend": {
            "class": "Application",
            "template": "generic",
            "backend-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
