kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-arcadia-refer
  namespace: arcadia-refer
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.30.0",
        "id": "arcadia-refer",
        "arcadia-refer": {
          "class": "Tenant",
          "refer": {
            "class": "Application",
            "template": "generic",
            "refer-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
