kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-arcadia
  namespace: arcadia
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.30.0",
        "id": "arcadia",
        "arcadia": {
          "class": "Tenant",
          "main": {
            "class": "Application",
            "template": "generic",
            "arcadia-vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "192.168.200.13"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "main-svc-pool"
            },
            "main-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          },
          "backend": {
            "class": "Application",
            "template": "generic",
            "backend-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          },
          "api": {
            "class": "Application",
            "template": "generic",
            "api-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          },
          "refer": {
            "class": "Application",
            "template": "generic",
            "refer-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
