kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-arch-endpoints
  namespace: f5-hub-1
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.36.0",
        "id": "cm-arch-endpoints",
        "cistest212": {
          "class": "Tenant",
          "iop-hot-deploy-verification": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "192.168.200.199"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "iop-hot-deploy-verification-svc_pool"
            },
            "iop-hot-deploy-verification-svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
