kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-test105
  namespace: test105
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "configmap-test105",
        "label": "configmap-test105",
        "test105": {
          "class": "Tenant",
          "test105": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_L4",
              "persistenceMethods": [ "source-address" ],
              "virtualAddresses": [
                "192.168.200.14"
              ],
              "virtualPort": 8877,
              "snat": "auto",
              "mirroring": "L4",
              "pool": "test105_app_svc_pool"
            },
            "test105_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8877,
                "serverAddresses": [ ]
              }
              ]
            }
          }
        }
      }
    }
