kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: cistest001
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.30.0",
        "id": "f5-hub01-a",
        "cistest001": {
          "class": "Tenant",
          "plbbanking-app": {
            "class": "Application",
            "template": "generic",
            "plbbanking-app-vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "iRules": ["plbbanking-app_irules"],
              "virtualAddresses": [
                "192.168.200.13"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "plbbanking-app-pool"
            },
            "plbbanking-app_irules": {
              "class": "iRule",
              "iRule": "when HTTP_REQUEST {\n  log local0. [HTTP::uri] \n  switch -glob [HTTP::uri] { \n    \"/gluebanking*\" { pool /cistest001/gluebanking-app/gluebanking-app-pool } \n    default { pool /cistest001/plbbanking-app/plbbanking-app-pool } \n  } \n}"
            },
            "plbbanking-app-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
              ]
            }
          },
          "gluebanking-app": {
            "class": "Application",
            "template": "generic",
            "gluebanking-app-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
