apiVersion: v1
kind: Namespace
metadata:
  name: cistest001
  labels:
    cis_scanner: cistest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plbbanking-app
  name: plbbanking-app
  namespace: cistest001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plbbanking-app
  template:
    metadata:
      labels:
        app: plbbanking-app
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: plbbanking-app
    cis.f5.com/as3-tenant: cistest001
    cis.f5.com/as3-app: plbbanking-app
    cis.f5.com/as3-pool: plbbanking-app-pool
  name: plbbanking
  namespace: cistest001
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: plbbanking-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gluebanking-app
  name: gluebanking-app
  namespace: cistest001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluebanking-app
  template:
    metadata:
      labels:
        app: gluebanking-app
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gluebanking-app
    cis.f5.com/as3-tenant: cistest001
    cis.f5.com/as3-app: gluebanking-app
    cis.f5.com/as3-pool: gluebanking-app-pool
  name: gluebanking
  namespace: cistest001
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gluebanking-app
  sessionAffinity: None
  type: ClusterIP
---
