apiVersion: v1
kind: Namespace
metadata:
  name: cistest014
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-2
  name: app-2
  namespace: cistest014
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - image: cloudadc/nginx-devops-demo:2.0.1
        name: backend
        ports:
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: cistest014
    cis.f5.com/as3-app: app-2
    cis.f5.com/as3-pool: app_2_svc_pool
  name: app-svc-2
  namespace: cistest014
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: app-2
  sessionAffinity: None
  type: ClusterIP
