kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-test001
  namespace: f5-hub-2
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true, 
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.36.0",
        "id": "cm-test001",
        "test001": {
          "class": "Tenant",
          "app-v1": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "192.168.200.11"
              ],
              "virtualPort": 80,
              "pool": "app-v1-svc-pool"
            },
            "app-v1-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
