apiVersion: v1
kind: Namespace
metadata:
  name: cistest12
  labels:
    cis.f5.com/zone: cistest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-1
  name: app-1
  namespace: cistest12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: cistest12
    cis.f5.com/as3-app: app
    cis.f5.com/as3-pool: app-svc-1_pool
  name: app-svc-1
  namespace: cistest12
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cis.f5.com/as3-tenant: cistest12
    cis.f5.com/as3-app: app
    cis.f5.com/as3-pool: app-svc-2_pool
  name: app-svc-2
  namespace: cistest12
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-1
  type: ClusterIP
