apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigip-ctlr-cccl
  namespace: bigip-ctlr
  labels:
    app: bigip-ctlr-cccl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigip-ctlr-cccl
  template:
    metadata:
      name: bigip-ctlr-cccl
      labels:
        app: bigip-ctlr-cccl
    spec:
      serviceAccountName: bigip-ctlr
      containers:
        - name: f5-test-1-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:2.5.0"
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 3
            exec:
              command:
              - curl
              - -k
              - -s
              - -o
              - /dev/null
              - https://192.168.200.204
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--namespace-label=cis_scanner_zone=zone_1",
            "--manage-configmaps=true",
            "--manage-ingress=false",
            "--log-level=INFO",
            "--bigip-url=192.168.200.204",
            "--insecure=true",
            "--bigip-partition=k8s",
            "--pool-member-type=cluster",
            "--agent=cccl"
            ]
