apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: f5-ipam-controller
  name: f5-ipam-controller
  namespace: bigip-ctlr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-ipam-controller
  template:
    metadata:
      labels:
        app: f5-ipam-controller
    spec:
      serviceAccount: bigip-ctlr
      containers:
      - args:
        - --orchestration=kubernetes
        - --ip-range='{"Dev":"192.168.200.11-192.168.200.15"}'
        - --log-level=INFO
        command: ["/app/bin/f5-ipam-controller"]
        image: f5networks/f5-ipam-controller:0.1.7 
        name: f5-ipam-controller
