kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cistest
  namespace: cistest001
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.30.0",
        "id": "f5-hub01-a",
        "cistest001": {
          "class": "Tenant",
          "app-svc-1-app": {
            "class": "Application",
            "template": "generic",
            "app-svc-1-app-vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.10.10.1"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "app-svc-1-app-pool"
            },
            "app-svc-1-app-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
              ]
            }
          },
          "app-svc-2-app": {
            "class": "Application",
            "template": "generic",
            "app-svc-2-app-vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.10.10.2"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "app-svc-2-app-pool"
            },
            "app-svc-2-app-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
              ]
            }
          },
          "app-svc-3-app": {
            "class": "Application",
            "template": "generic",
            "app-svc-3-app-vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.10.10.3"
              ],
              "snat": "self",
              "virtualPort": 80,
              "pool": "app-svc-3-app-pool"
            },
            "app-svc-3-app-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
