apiVersion: v1
kind: Service
metadata:
  annotations:
    cis.f5.com/ipamLabel: Dev
    cis.f5.com/health: '{"interval": 10, "timeout": 31}'
  labels:
    app: app
  name: app-svc-lb
  namespace: test102
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  sessionAffinity: None
  type: LoadBalancer
