kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-test001
  namespace: test001
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true, 
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.30.0",
        "id": "cm-test001",
        "test001": {
          "class": "Tenant",
          "app-v1": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
               "iRules": ["test001_app-v1-svc_irules"],
              "virtualAddresses": [
                "192.168.200.13"
              ],
              "virtualPort": 80
            },
            "app-v1-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            },
            "test001_app-v1-svc_irules": {
              "class": "iRule",
              "iRule": "when HTTP_REQUEST {\n  if {([URI::query ?[URI::query [HTTP::uri]] name]) equals \"1010\"} {\n    pool /test002/app-v2/app-v2-svc-pool \n  } else {\n    pool /test001/app-v1/app-v1-svc-pool \n  } \n}"
            }
          }
        }
      }
    }
