kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-test002
  namespace: test002
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true, 
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.30.0",
        "id": "cm-test002",
        "test002": {
          "class": "Tenant",
          "app-v2": {
            "class": "Application",
            "template": "generic",
            "app-v2-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
