kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-test003
  namespace: f5-hub-2
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.36.0",
        "id": "test003",
        "test003": {
          "class": "Tenant",
          "main": {
            "class": "Application",
            "template": "generic",
            "test003-vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "192.168.200.12"
              ],
              "snat": "self",
              "virtualPort": 80,
              "iRules": ["test003-routing"],
              "pool": "main-svc-pool"
            },
            "main-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            },
            "test003-routing": {
              "class": "iRule",
              "iRule": "when HTTP_REQUEST {\n  if { [HTTP::uri] starts_with \"/api\" } {\n    pool /test003/api/api-svc-pool \n  } elseif { [HTTP::uri] starts_with \"/files\" } {\n    pool /test003/backend/backend-svc-pool \n  } elseif { [HTTP::uri] starts_with \"/app3\" } {\n    pool /test003/refer/refer-svc-pool \n  } else {\n    pool /test003/main/main-svc-pool \n  }\n}"
            }
          },
          "backend": {
            "class": "Application",
            "template": "generic",
            "backend-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          },
          "api": {
            "class": "Application",
            "template": "generic",
            "api-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          },
          "refer": {
            "class": "Application",
            "template": "generic",
            "refer-svc-pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
