kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-2509
  namespace: f5-hub-3
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.36.0",
        "id": "cm-2509",
        "cistest301": {
          "class": "Tenant",
          "Shared": {
            "class": "Application_Shared",
            "template": "shared",
            "app-1_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-2509
  namespace: f5-hub-4
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.36.0",
        "id": "cm-2509",
        "cistest302": {
          "class": "Tenant",
          "Shared": {
            "class": "Application_Shared",
            "template": "shared",
            "app-1_app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
