apiVersion: v1
kind: Namespace
metadata:
  name: cafe
  labels:
    cis_scanner_zone: zone_1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: cafe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: cloudadc/cafe:1.0
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
    cis.f5.com/as3-tenant: cafe
    cis.f5.com/as3-app: app
    cis.f5.com/as3-pool: app_app_svc_pool
  name: app-svc
  namespace: cafe
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  type: ClusterIP
