kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-ttcp
  namespace: ttcp
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.30.0",
        "id": "configmap-ttcp",
        "label": "configmap-ttcp",
        "ttcp": {
          "class": "Tenant",
          "app": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_L4",
              "persistenceMethods": [ "source-address" ],
              "virtualAddresses": [
                "192.168.200.14"
              ],
              "virtualPort": 5001,
              "snat": "self",
              "mirroring": "L4",
              "pool": "app_ttcp_svc_pool"
            },
            "app_ttcp_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp-half-open"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 5001,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
