apiVersion: v1
kind: Namespace
metadata:
  labels:
    cis_scanner_zone: zone_1
  name: ttcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ttcp
  name: ttcp
  namespace: ttcp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ttcp
  template:
    metadata:
      labels:
        app: ttcp
    spec:
      containers:
      - image: cloudadc/ttcp:1.12-1
        name: ttcp
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ttcp
    cis.f5.com/as3-tenant: ttcp
    cis.f5.com/as3-app: app
    cis.f5.com/as3-pool: app_ttcp_svc_pool
  name: ttcp-svc
  namespace: ttcp
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: ttcp
  sessionAffinity: None
  type: ClusterIP
